location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_llcp
    name: mrs_llcp
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_llcp
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_llcp
    name: mrs_llcp
    rev: 4f11e9ead40dd97b7c590c84ce995a3856c39d44
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: mrs_llcp
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
